### ISSUE TITLE
TGLBaseSceneObject.PointTo method apparently with wrong behaviour

### ISSUE THREAD

**Issue by jersonSeling** [GLScene/GLScene#1]
When using the **TGLBaseSceneObject.PointTo** method with the **target coordinate positioned in the same orientation that the up vector**, the object does not become properly aligned. In different orientations it works fine.

The same proposal **TGLCamera.RotateObject** method works perfectly.

May be, they could be merged in just one method.

I builded a little demo showing the problem.
Just click in the button '_Reproduce problem (wrongly aligned beam)_'.

[problem_reprodution_delphi.zip](https://github.com/GLScene/GLScene/files/4825878/problem_reprodution_delphi.zip)

**Comment by GLScene** [comment]
jersonSeling, I've reproduced a beam allignment in your demo and not found differences. Appearantly you need to create more clear tests with your assumption of what unit of GLScene should be edited.

**Comment by jersonSeling** [comment]
I downloaded the most updated GLScene version and reproduce the demo, the wrong behaviour continues.

To be more clear, I created a image explaining the wrong alignment problem:

![explanation](https://user-images.githubusercontent.com/20733599/86354200-f608fd80-bc3e-11ea-8fce-d1562b9972fa.png)

**Comment by GLScene** [comment]
Ok,
That's more clear I'll try  to fix it.

**Comment by GLScene** [comment]
kersonSeling,
I have no idea why you are not using ABeam.PointTo(p1, p2) in AddBeam
![PointTo](https://user-images.githubusercontent.com/66052716/86379707-d51ec780-bc93-11ea-805b-e5914fd5ad5c.jpg)
;

**Comment by jersonSeling** [comment]
Because p2 is a tip coordinate, and not a Up vector.
Then I pass the beam Up vector like the method declaration asks.

```pascal
procedure TGLBaseSceneObject.PointTo(const ATargetObject: TGLBaseSceneObject;  const AUpVector: TVector);
procedure TGLBaseSceneObject.PointTo(const AAbsolutePosition, AUpVector:  TVector);
```
I don't know why use p2 as a Up vector work.

**Comment by GLScene** [comment]
Yes,
it happens only when p2=(0,0,0). It seems work right if p2(0.01,0,0). We need to fix it.

**Comment by jersonSeling** [comment]
I think that could be possible transfer pieces from the code of TGLCamera.RotateObject to the TGLBaseSceneObject.PointTo, correcting it.
And make TGLCamera.RotateObject use the TGLBaseSceneObject.PointTo, eliminating duplicate code.

**Comment by GLScene** [comment]
Well jersonSeling,
You almost fixed the bug, so while I have no much time now retired after seventy
you can corrent the procedures in GLScene unit and apply here your variant.
But it should also corrently work with Pointto and SmoothNavigator projects in ..Delphi\movements  demos. 
Pavel

**Comment by jersonSeling** [comment]
Ok, this weekend I will try make a merge request here with this fix.
Thx for everything!

**Comment by GLScene** [comment]
Jerson,
Please, add and show it in your demo code.

**Comment by jersonSeling** [comment]
Hi, I don't have permission to add on GLScene main repository:

![acess](https://user-images.githubusercontent.com/20733599/86519089-cb20d400-be0d-11ea-8501-19795d2258f6.png)

I just added on my [GLScene fork](https://github.com/jersonSeling/GLScene).

But I tested and worked perfectly.

Built a automatic test demo like a unit test too.
[pointto_tests_2.zip](https://github.com/GLScene/GLScene/files/4873655/pointto_tests_2.zip)

Without the fix.
![ERROR](https://user-images.githubusercontent.com/20733599/86519053-6f564b00-be0d-11ea-94d8-b2eac986a050.png)

With the fix:
![FIX](https://user-images.githubusercontent.com/20733599/86519054-70877800-be0d-11ea-953a-08dd0d480ed4.png)

**Comment by GLScene** [comment]
Fixed in GLScene unit, Thnx

**Comment by GLScene** [comment]
Fixed in trunk
