### ISSUE TITLE
Which soft can edit/export HTFFile？

### ISSUE THREAD

**Issue by cn17173** [GLScene/GLScene#18]
In the demo of Archipelago,GLHeightTileFileHDS need the HTFFile（ Islands.htf）, which soft can edit/export HTFFile？
The following Link is not worked.
- Terrain elevation map and textures : Mattias Fagerlund
  (http://www.cambrianlabs.com/Mattias/), heightmap and sedimentation
  map created by World Machine from Stephen Schmitt
  (http://students.washington.edu/sschmitt/world/)

**Comment by GLScene** [comment]
cn17173
Look also at https://github.com/GLScene/GLScene/tree/master/Demos/utilities/HTFUtils
pw

**Comment by cn17173** [comment]
Thanks.

**Comment by cn17173** [comment]
I have found "HTFViewer.exe" and it worked. But how to set parameters of TerrainPack.exe?
'' is not a vaild integer value.[http://scplot.cn:8888/glscene.png](url)
