### ISSUE TITLE
Problems in several text formats reading Floats in non-US regional settings

### ISSUE THREAD

**Issue by macropoloxxi** [GLScene/GLScene#22]
Hi Pavel!

I have sarted to try the GLTF import. Generating the GLTFs from Blender objects (native export to GLTF 2.0) I'm unable to import none of the examples I had into GLScene.

Of course I have added the GLS.FileGLTF and GLS.FileGLB in the uses clause, but I keep receiving the classical message:

![image](https://user-images.githubusercontent.com/16530111/201915198-29fd0872-aa70-4ec5-83c0-0a41b63abd2f.png)

I'm using the last code you pointed in: https://github.com/GLScene/GLScene/blob/master/Source/GLS.FileGLTF.pas

By the way, this unit shouldn't register 'gltf' extension instead of re-registering 'glb'? The original code in GLS.FileGLTF registers this:

RegisterVectorFileFormat('glb', 'Binary glTF files', TGLTFVectorFile);

If you have other models or other sources I can help on testing with GLTF please share them with me.

GLTF imports would natively accept animations too, right?

**I've found in several Units conversions using StrToFloatDef that are going to fail when system is non in US locale.  Do you want me to help by adding them the fs.DecimalSeparator := '.' used in FileSMD?**

Regards, Pablo.

**Comment by GLScene** [comment]
Hi, 
I've registered gltf vector format and added cube, animatedcube and duck to media, to debug importing in GLSceneViewer, so you could go further in GLS.FileGLTF. 

As for localization, yes it better to correct, but may be using from  our unit
GLS.PersistentClasses.pas -

TGLTextReader.ReadFloat: Extended;
var
  oldDc: Char;
begin
  ReadLine(cVTInteger);
  oldDc := FormatSettings.DecimalSeparator;
  FormatSettings.DecimalSeparator := '.';
  Result := StrToFloat(FData);
  FormatSettings.DecimalSeparator := oldDc;
end;
 
Pavel

**Comment by GLScene** [comment]
Look at gltf static models and animated cube, to start import in gls
![CubeAndDuck_gltf](https://user-images.githubusercontent.com/66052716/202166721-5a05b10b-9522-4a4f-8a3d-b52525721d39.png)
![StartReadingGLTF_GLB](https://user-images.githubusercontent.com/66052716/202166745-4a8ecbe9-80e2-4838-a1b3-bc1178275b6b.png)

**Comment by macropoloxxi** [comment]
Thank you Pavel.

I've found those models. I receive in any of them (having or not animations) this message:

![image](https://user-images.githubusercontent.com/16530111/202230708-b0bf3c99-9670-4284-ad49-570b7eeeda38.png)

Those 3D models in gltf are supposed to work now or not yet?

Regards, Pablo

**Comment by GLScene** [comment]
You wrote -
"Those 3D models in gltf are supposed to work now or not yet?"
Yes, of course, if you're working in win10/11 then double click by left mouse button on the gltf model and it will be opened in  3D Builder as in picture. But the code in GLS.FileGLTF needs to be rewritten for importing as for smd or md2 formats. 
![CubeIn3DBuilder](https://user-images.githubusercontent.com/66052716/202244363-1aced599-f317-44d1-8de0-a0d109112e30.png)
The functions for localization could be included in GLS.Utils unit.
Salute, Pavel

**Comment by macropoloxxi** [comment]
Hi Pavel!

I have added the GLStrToFloatDef functions to GLS.Utils in it's three overloads.

I have converted all the uses made of them in the different Units so for any text to float conversion, the proper universal decimal separator '.' is used:

[SourceChanged.zip](https://github.com/GLScene/GLScene/files/10031189/SourceChanged.zip)

I only left one use of System.SysUtils.StrToFloatDef function here, because the value comes from an InputDlg and it is expected to be formatted as the Windows locale:

```
class function TGLProcTextureNoiseTIE.Edit(aTexImage: TGLTextureImage): Boolean;
var
  p: Integer;
  buf: String;
begin
  with aTexImage as TGLProcTextureNoise do
  begin
    buf := InputDlg(TGLProcTextureNoise.FriendlyName, 'Enter size', Format('%d x %d', [Width, Height]));
    p := Pos('x', buf);
    if p > 0 then
    begin
      Width := StrToIntDef(Trim(Copy(buf, 1, p - 1)), 256);
      Height := StrToIntDef(Trim(Copy(buf, p + 1, MaxInt)), 256);
      buf := InputDlg(TGLProcTextureNoise.FriendlyName, 'Minimum Cut', IntToStr(MinCut));
      MinCut := StrToIntDef(buf, 0);
      buf := InputDlg(TGLProcTextureNoise.FriendlyName, 'Noise Sharpness', FloatToStr(NoiseSharpness));
      //By PAL, this has to be StrToFloatDef using Windows locale because comes from a Dialog
      NoiseSharpness := StrToFloatDef(buf, 0.9);
      buf := InputDlg(TGLProcTextureNoise.FriendlyName, 'Random Seed', IntToStr(NoiseRandSeed));
      NoiseRandSeed := StrToIntDef(buf, 0);
      RandSeed := NoiseRandSeed;
      buf := InputDlg(TGLProcTextureNoise.FriendlyName, 'Generate Seamless Texture (0,1)', IntToStr(Ord(Seamless)));
      Seamless := (buf <> '0');
      Result := True;
      Invalidate;
    end
    else
    begin
      InformationDlg('Invalid size');
      Result := False;
    end;
  end;
end;
```

Regard, Pablo.

**Comment by GLScene** [comment]
Well, Pablo,
I've updated gls repos on Github and SF
PW
