### ISSUE TITLE
The File "License.txt" in the Help directory is not consistent with the MPL v2.0 license

### ISSUE THREAD

**Issue by Dr-wood** [glscene/GLScene#28]
In reviewing the source code for licensing we found that the interpretation of the Mozilla Public License Version v2.0 (MPL v2.0) license in the Help Directory "License.txt" file is not consistent with the actual MPL v2.0 license it is supposed to be simplifying where it states in part: "...GLScene is distributed under Mozilla Public Licence (MPL 2.0), which means, in short, that it is free for both freeware and commercial use.  The code is still copyrighted (in that it isn't public domain), but you can use it in products with closed or open-source freely. The only requirements are:
* Acknowledge GLScene is used somewhere in your application (in an about box, credits page or printed manual, etc.
with at least a link to http://glscene.org or https://github.com/glscene)
* Modifications made to GLScene units must be made public (no need to publish the full code, only to state which parts were altered, and how), but feel welcome to open-source your code if you so wish."
  
The Mozilla Public License Version v2.0 license requires (in Sections 3.1 and 3.2) that  anyone who modifies the original source code to do the following things upon distribution of the executable form of the code:
1. license the modification under the MPL v2.0 license, 
2. redistribute the source source code by having it accompany the delivery, or
3. providing notice to the recipient about how they can obtain a copy of the source code that makes up the modified executable.

We would appreciate your clarification of this discrepancy and actions to alleviate any future misunderstandings.
Please reply to myself Dr-Wood through the GitHub users link
Thank you
Chris

**Comment by glscene** [comment]
Yes, there is a difference, that's right. What are your license suggestions, go back to version 1.0 or leave Mozilla 2.0? briefly explain why you need it, and also if you use either MIT/zlib/ licenses... along with your private code. Offer.

**Comment by Dr-wood** [comment]
The easiest fix in my opinion would be to remove the License.txt file in the Help Directory as the guidance there is not really a license  and does not provide guidance that is consistent with the license that you have chosen (the MPL 2.0) which is a weak copyleft license.

**Comment by Dr-wood** [comment]
In the "License.txt" file perhaps you could use some of the words from the MPL site (https://www.mozilla.org/en-US/MPL/2.0/)and call the txt file by another name maybe something like "MPL 2.0 distribution requirements summary" or similar and attribute the copied text to the Mozilla Foundation.   In the text you might copy their explanation of what the Section 3.0 (3.1, 3.2. 3.3...) and Section 10 mean in the *****.txt file.

This is only Technical advice and is not in any way to be considered as Legal advice, if you require Legal advice please consult with an Attorney as I am not a Lawyer.

**Comment by glscene** [comment]
Well, extra MPL 2.0 license file deleted

**Comment by Dr-wood** [comment]
Thank you very much. I am assuming that the application version remained the same?  I really appreciate your quick response and action.
