### ISSUE TITLE
In the GLScene v2.3 Software a NVIDIA Proprietary License was found in the "ScalarProduct-kernel.cu" file

### ISSUE THREAD

**Issue by Dr-wood** [glscene/GLScene#29]
Hello again:  During licensing review we discovered that there is a proprietary NVIDIA license in the software named above.  Because of this we cannot use your software.  The Scalar sub-directory contains 5 files all with the word "Scalar" in the filename, most likely indicating that they are also NVIDIA-developed code.  

The path to the file is: GLScene-master.zip\GLScene-Master\Examples\Demos\computing\ScalarProduct\ScalarProduct-kernel.cu.

Because these files are considered Proprietary by NVIDA and cannot be used without a license they would likely be a risk for your product to retain unless you have a specific license grant from NVIDIA.  If that is the case and you do have such a license grant then you might want to include that document in the ScalarProduct  folder.  To keep your distribution compliant with the licensing and as more organizations begin performing open-source code scanning to generate SBOMs you may want to consider removing this "example" sub-directory.   

The license text is:
/*
 * Copyright 1993-2009 NVIDIA Corporation.  All rights reserved.
 *
 * NVIDIA Corporation and its licensors retain all intellectual property and 
 * proprietary rights in and to this software and related documentation. 
 * Any use, reproduction, disclosure, or distribution of this software 
 * and related documentation without an express license agreement from
 * NVIDIA Corporation is strictly prohibited.
 *
 * Please refer to the applicable NVIDIA end user license agreement (EULA) 
 * associated with this source code for terms and conditions that govern 
 * your use of this NVIDIA software.
 * 
 */

**Comment by Dr-wood** [comment]
If you would remove the "ScalarProduct" sub-directory from the Example files that would correct the issue and we would be able to utilize the software.

**Comment by glscene** [comment]
Hello Dr-wood,
This kerrnel.cu file was included in v.1.1 many years ago with uncorrected license text, so now it has the same agreement from NVideo as in source code CUDA.FourierTransform.pas. 
Done
