### ISSUE TITLE
Refactor installation documentation to remove duplication of identical but, currently, mismatched steps

### ISSUE THREAD

**Issue by mrandreastoth** [glscene/GLScene#30]
The installation document Installation.pdf contains two nearly identical sections describing the installation of GLScene, one starting on page 1 and the other starting on page 4 with the last one containing additional information pertaining to the installation of the "AdvDemos Earth" demo.

Having commonality duplicated not only leads to unnecessarily having to maintain both of the commonalities but can lead to them becoming out-of-sync with each other, which has actually happened as demonstrated by differences in the installation steps, for example, one section refers to the same step, but at a different step number, using "compile all from here" in the text while the other refers to the same thing using a screenshot highlighting "build all from here" instead. This not only results in the sections being inconsistent and out-of-sync with each other, but may lead to confusion to the reader.

Suggest refactoring the document by merging the installation instructions from both sections turning it into one set of steps only with the section following this only describing the installation steps necessary for the demo.

**Comment by glscene** [comment]
Thanks for noticing the duplication. I updated the file.
