### ISSUE TITLE
License differs from original

### ISSUE THREAD

**Issue by mrandreastoth** [GLScene/GLScene#6]
For some reason the license has been changed from the original GLScene license which used MIT 1.1. It is now MIT 2.0. Is this change correct/legal?

**Comment by GLScene** [comment]
Hi Andreas, is there really a big difference? 
If so, the next version may be 1.1 again. 
Pavel

**Comment by mrandreastoth** [comment]
> 
> 
> Hi Andreas, is there really a big difference?
> If so, the next version may be 1.1 again.
> Pavel

I really don't know as I cannot find any information about the difference between the two versions (yes, I know, I could diff 1.1 with the 2.0 version provided ☺️). In fact, nowhere I have looked appear to make any mention of versions of the MIT license even though we can easily conclude that at least two must exist because of the point version of 1.1 suggesting there is a lower version of the license.

But I digress...

My real concern, and the reason for this ticket, is that license changes, however small, have much impact and causes issues in processes including review and release cycles due to legal getting involved. As such, if the reason for the version change isn't clearly justified, I suggest reverting back to the original. But then I'm no lawyer and no expert in licenses. It's just my two cents worth ☺️.

**Comment by GLScene** [comment]
There is only Mozilla Public License 2.0 to add automatically in project's settings in Github without Mozilla 1.1 so let it be as it is now. I don't want to edit it back manually. May be later. Thank you Andreas.
