### ISSUE TITLE
GLScene doesn't support MTL file format?

### ISSUE THREAD

**Issue by SlastyonArtyom** [GLScene/GLScene#7]
GLScene doesn't support MTL file format?

**Comment by jseling** [comment]
https://github.com/GLScene/GLScene/blob/a878c9dbcd36a9525e8f60eea786b5a99dd9a540/Source/GLS.FileOBJ.pas#L87

**Comment by SlastyonArtyom** [comment]
> https://github.com/GLScene/GLScene/blob/a878c9dbcd36a9525e8f60eea786b5a99dd9a540/Source/GLS.FileOBJ.pas#L87

Thank you for responce.
